# Generated by Django 3.2.4 on 2021-06-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='single', max_length=20),
        ),
    ]
