# Generated by Django 3.2.4 on 2021-06-13 01:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20210613_0754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexam',
            unique_together={('user', 'exam')},
        ),
    ]
