# Generated by Django 3.2.4 on 2021-06-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userexam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answers',
            field=models.ManyToManyField(to='quiz.QuestionChoice'),
        ),
    ]
