# Generated by Django 3.2.4 on 2021-06-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questionanswer_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='choice',
        ),
    ]
