# Generated by Django 3.2.4 on 2021-06-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_questionanswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='question_choices', to='quiz.QuestionChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.ManyToManyField(related_name='question_answer_choices', to='quiz.QuestionChoice'),
        ),
    ]
