# Generated by Django 3.2.4 on 2021-06-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210614_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='quiz.question'),
        ),
    ]
