# Generated by Django 3.2.4 on 2021-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_questionchoice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='is_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='question_choices', to='quiz.QuestionChoice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choices',
            field=models.ManyToManyField(blank=True, related_name='question_answer_choices', to='quiz.QuestionChoice'),
        ),
    ]
