# Generated by Django 3.2.4 on 2021-06-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210614_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='is_correct',
        ),
    ]
